import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "VEENOVERSE",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="w-full  flex justify-center bg-transparent">
        <div>
                <div className="w-[375px] min-h-[785px] border-x-2">
                    {children}
                </div>
        </div>
        </body>
        </html>
    );
}
